FROM haskell:9.8
# RUN apt update && apt install emacs -y
# RUN git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/plfa/plfa.github.io /root/plfa

# RUN cabal update && cabal install Agda-2.6.3
# WORKDIR /root/plfa